/* Generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "language-reader",
  "name": "Lang Lens",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Write me a short A2 Spanish story about football",
      "does": "Generates a graded story and opens it."
    },
    {
      "say": "Mark every word in this story as known",
      "does": "Updates your vocabulary."
    },
    {
      "say": "Review my words with fill-in-the-gap",
      "does": "Starts a cloze review session."
    }
  ]
};
